"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "az" | "ru";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    en: {
        // Project Info
        projectName: "TripMind",
        tagline: "Explore the world your way",

        // Navigation
        home: "Home",
        about: "About",
        favorites: "Favorites",
        profile: "Profile",

        // Auth placeholder removed

        // Hero
        heroTitle: "Your Personal AI Travel Architect",
        heroSubtitle: "Deeply personalized travel itineraries powered by advanced intelligence.",
        analyzing: "Analysing your profile...",
        calculating: "Calculating...",
        startNew: "Start New Analysis",
        generateBtn: "Generate Deep Travel Plan",
        travelDate: "Travel Date",

        // Forms
        budget: "Budget",
        dates: "Dates",
        nationality: "Nationality",
        location: "Location",
        profession: "Profession",
        food: "Food Preference",
        interests: "Interests",
        special: "Special Requests",
        planSettings: "Plan Settings",
        travelBasics: "Travel Basics",
        personalDetails: "Personal Details",
        preferences: "Preferences",
        goals: "Interests & Goals",
        enterCountry: "Enter Country Name",
        findCountry: "Find My Destination",
        fromPlaceholder: "City or Country",
        toPlaceholder: "Destination City",
        interestsPlaceholder: "History, Nature, Adventure...",
        foodPlaceholder: "Vegan, Local, Fine Dining...",
        specialRequestsPlaceholder: "Any special needs or private wishes...",
        selectFoodType: "Food Preference",
        searchBtn: "Discover Now",
        backToDash: "Back to Dashboard",
        days: "Days",
        travelersLabel: "Travelers",
        from: "From",
        to: "To",
        travelMode: "Travel Mode",
        accommodationType: "Accommodation Type",
        travelClass: "Travel Class",
        budgetPreference: "Budget Preference",
        season: "Season",
        specialRequests: "Special Requests",
        plane: "Plane",
        car: "Car",
        bus: "Bus",
        train: "Train",
        luxury: "Luxury",
        standard: "Standard",
        eco: "Eco",
        economy: "Economy",
        business: "Business",
        firstClass: "First Class",
        low: "Low",
        medium: "Medium",
        high: "High",
        summer: "Summer",
        winter: "Winter",
        spring: "Spring",
        autumn: "Autumn",
        any: "Any",

        // Plan Display
        recommended: "Recommended Destinations",
        breakdown: "Budget Breakdown",
        attractions: "Top Attractions",
        foodRecs: "Food Recommendations",
        tips: "Travel Tips",
        upgrade: "Upgrade Your Experience",
        upgradeBtn: "Upgrade Now",
        flight: "Flight",
        hotel: "Hotel",
        foodItem: "Food",
        activities: "Activities",

        // Gastro Guide Results
        budgetAnalysisReady: "Budget Analysis Ready",
        curatedByAgent: "Curated by TripMind Budget Agent",
        total: "Total",

        // Service Cards
        explore: "Explore",
        tripPlannerTitle: "Trip Planner",
        tripPlannerDesc: "Detailed itineraries and budget analysis tailored to your preferences.",
        gastroGuideTitle: "Gastro Guide",
        gastroGuideDesc: "Calculate your travel expenses and get a detailed budget breakdown for your trip.",
        spotFinderTitle: "Spot Voyager",
        spotFinderDesc: "Unlock the most iconic and hidden landmarks of any country with a single search.",
        foodFinderTitle: "Food Finder",
        foodFinderDesc: "Discover the perfect meal in the country you are in.",
        foodCountryLabel: "Country & City",
        foodCountrySubLabel: "Country/city you are in or going to",
        foodCountryPlaceholder: "Example: Rome, Italy",
        foodTasteLabel: "Food Taste",
        foodBudgetLabel: "Budget",
        foodBudgetPlaceholder: "Write your budget",
        foodSpecialLabel: "Special Requirements",
        foodGenerateBtn: "Analyze Food Options",
        termsTitle: "Terms & Scientific Intelligence Policy",
        termsIntro: "Our system operates on advanced neural linguistic models and statistical entropy analysis.",
        termsSection1: "AI Ethical Framework",
        termsSection2: "Data Trajectory & Entropy",
        termsSection3: "Algorithm Responsibility",
        termsSection4: "Neural Mapping Accuracy",
        cookiesTitle: "Cookie Policy",
        cookiesContent: "Our system operates on a zero-tracking principle. We do not use any cookies or local tracking mechanisms to store your personal session data.",
        privacyTitle: "Privacy Policy & AI Disclosure",
        privacyIntro: "Your data privacy is governed by neural processing ethics.",
        aiDisclaimer: "IMPORTANT: This analysis is generated by Artificial Intelligence. While highly advanced, AI can occasionally provide inaccurate or outdated information. Please verify critical details independently.",
        termsS1Content: "TripMind AI neural networks are based on moral-ethical choice matrices. Our algorithm analyzes the digital equivalent of human culture to create a global data symbiosis. Each recommendation is aligned with the principles of sociological determinism.",
        termsS2Content: "Data collection and processing are aimed at reducing statistical entropy. User inputs are protected by quantum-resistant encryption and remain anonymous throughout the neural mapping trajectory. We create ordered travel structures from digital chaos.",
        termsS3Content: "While algorithmic decisions are autonomous, they are continuously calibrated with macro-economic fluctuations and geopolitical vectors. The 99.9% data accuracy in the TripMind AI system is ensured by statistical probability theory and empirical cross-validation.",
        termsS4Content: "During the neural mapping process, the digital reflection of geographical coordinates and cultural artifacts is carried out through heuristic models. We don't just plan user experiences; we reconstruct them with mathematical precision.",
        scientificQuote: "Intelligence is the ability to adapt to change, but artificial intelligence is the ability to predict the entropy of human desires.",
        privacyPoint1Title: "Data Collection",
        privacyPoint1Desc: "We only process the parameters you enter for analysis (country, interests, etc.).",
        privacyPoint2Title: "Third Parties",
        privacyPoint2Desc: "Your data is not sold to any advertising companies or third parties. Only AI models (Groq/Gemini) are used for analysis.",
        zeroStorageTitle: "Zero Storage Policy",
        zeroStorageDesc: "We do not store your personal travel plans permanently on our servers. Each analysis is temporary and is deleted when the session ends.",
        favoritesTitle: "My Favorite Destinations",
        favoritesSubtitle: "Track your dream locations on the interactive world map.",
        visitedCount: "Visited Countries",
        wishlistCount: "Wishlist",
        exploreMap: "Explore Map",
        addCountry: "Add Country",
        noFavorites: "You haven't added any favorites yet.",
        statsCompletion: "Completion",
        chooseContinent: "Choose your continent",
        englishLevel: "English Proficiency Level",
        budgetUSD: "Travel budget in USD",
        continentEurope: "Europe",
        continentAsia: "Asia",
        continentAfrica: "Africa",
        continentNAmerica: "North America",
        continentSAmerica: "South America",
        continentOceania: "Australia/Oceania",
        tripArchitectTitle: "Trip Architect",
        tripArchitectDesc: "Find the perfect country based on your budget and language proficiency.",
        tripArchitectSub: "Custom AI logic to find your perfect destination based on budget, location, and language proficiency.",
        architectureComplete: "Architecture Complete",
        calibratedByAI: "Precisely Calibrated for you by AI",
        step: "Step",
        nextStep: "Next Step",
        prevStep: "Back",
        lastStep: "Last Step",
        analyzeGenerate: "Analyze & Generate",
        englishA1Desc: "Advanced AI will use very simple sentences for you.",
        englishC2Desc: "Advanced AI will provide high-level professional narrative.",
        englishDefaultDesc: "AI will calibrate its recommendation style to your proficiency.",
        recommendedCountryLabel: "Recommended Country",
        attractionsActivitiesLabel: "Attractions & Activities",
        englishLevelAdviceLabel: "English Level Advice",
        budgetAnalysisAdviceLabel: "Budget Analysis & Advice",
        tailoredNarrative: "TAILORED NARRATIVE FOR YOUR PROFICIENCY",
        strategicTravelFinance: "Strategic Travel Finance",

        // Food Taste Options
        tasteMeat: "Meat lover",
        tasteVegetarian: "Vegetarian",
        tasteVegan: "Vegan",
        tasteSeafood: "Seafood lover",
        tasteSweet: "Sweet lover",
        tasteSpicy: "Spicy lover",
        tasteHealthy: "Healthy eating",
        tasteStreet: "Street food lover",
        tasteLuxury: "Luxury restaurant lover",
        tasteTraditional: "Traditional local cuisine",

        // Special Requirements Options
        reqHalal: "Halal required",
        reqGlutenFree: "Gluten-free",
        reqLactoseFree: "Lactose-free",
        reqAllergy: "I have an allergy",

        // Tags
        meatLover: "Meat Lover",
        vegetarian: "Vegetarian",
        vegan: "Vegan",
        halal: "Halal",
        history: "History & Culture",
        adventure: "Adventure & Nature",

        // Interest Tags
        interestAdventure: "Adventurer",
        interestHistorian: "Historian",
        interestNature: "Nature Lover",
        interestTech: "Tech Enthusiast",
        interestSport: "Sportsman",
        interestMusic: "Music Lover",
        interestCinema: "Cinephile",
        interestCreative: "Creative",
        interestTraveler: "Traveler",
        interestGastronome: "Gastronome",

        // Food Types
        foodMeat: "Meat",
        foodMix: "Mix",
        foodVegetarian: "Vegetarian",

        // Meals
        mealsPerDay: "Meals Per Day",

        // About Page
        aboutTitle: "Who Are We?",
        aboutDesc: "We are an AI-powered platform created to make travel smarter, more personal, and more accessible. Our goal is for people to find their ideal travel plan based on their budget and taste without hours of research.",
        aboutSystemDesc: "Our system prepares individual offers by analyzing user interests, budget, cultural compatibility, and even food taste.",
        missionTitle: "Our Mission",
        missionDesc: "To create a personalized and accessible travel experience for everyone. We believe travel isn't just about moving—it's a life experience when planned right.",
        howItWorksTitle: "How It Works?",
        howPoint1: "Analyzes the budget",
        howPoint2: "Selects destinations based on interests",
        howPoint3: "Suggests special places by profession",
        howPoint4: "Finds food matching national taste",
        howPoint5: "Estimates real costs",
        howPoint6: "Optimizes for season and date",
        whyUsTitle: "Why Us?",
        whyUsDesc: "Because we don't just say 'where you can go.' We understand who you are and tailor travel to you.",
        visionTitle: "Our Future Vision",
        visionDesc: "Our goal is to make AI-based personal travel planning accessible globally and help people make travel decisions easier, faster, and more accurately.",
        // Footer Additional
        startExploring: "Start Exploring Now",
        welcome: "Welcome",
        planTitle: "Choose Your Plan",
        freePlan: "Free",
        diamondPlan: "Diamond",
        goldPlan: "Gold",
        planMonth: "/ mo",
        planCurrent: "Current Plan",
        planUpgrade: "Upgrade",
        planFreeF1: "3 AI Plans / day",
        planFreeF2: "Basic destinations",
        planFreeF3: "Standard support",
        planDiamondF1: "30 AI Plans / day",
        planDiamondF2: "All destinations",
        planDiamondF3: "Priority support",
        planDiamondF4: "Budget analytics",
        planGoldF1: "Unlimited AI Plans",
        planGoldF2: "All destinations",
        planGoldF3: "24/7 VIP support",
        planGoldF4: "Full analytics",
        planGoldF5: "Custom itineraries",
        company: "Company",
        supportText: "Support",
        privacyPolicy: "Privacy Policy",
        contact: "Contact",
        helpCenter: "Help Center",
        community: "Community",
        feedback: "Feedback",
        footerTagline: "AI-Driven Travel Intelligence",
        footerSubtitle: "Experience the future of global exploration.",
        security: "Security",
        terms: "Terms",
        systemsOperational: "Systems Operational",
        brandSubtitle: "Global AI Architect",
    },
    az: {
        // Project Info
        projectName: "TripMind AI",
        tagline: "Sizin Şəxsi AI Səyahət Köməkçiniz",

        // Navigation
        home: "Ana Səhifə",
        about: "Haqqımızda",
        favorites: "Sevimlilər",
        profile: "Profil",

        // Auth placeholder removed

        // Hero
        heroTitle: "Sizin Şəxsi AI Səyahət Memarınız",
        heroSubtitle: "Süni intellekt tərəfindən hazırlanmış dərindən fərdiləşdirilmiş səyahət planları.",
        analyzing: "Hesablanır...",
        calculating: "analiz edilir",
        startNew: "Yeni Analiz",
        generateBtn: "Dərin Səyahət Planı Yarat",
        travelDate: "Səyahət Tarixi",

        // Forms
        budget: "Büdcə",
        dates: "Tarixlər",
        nationality: "Vətəndaşlıq",
        location: "Məkan",
        profession: "Peşə",
        food: "Qida Üstünlüyü",
        interests: "Maraqlar",
        special: "Xüsusi İstəklər",
        planSettings: "Plan Parametrləri",
        travelBasics: "Səyahət Əsasları",
        personalDetails: "Fərdi Məlumatlar",
        preferences: "Üstünlüklər",
        goals: "Maraqlar və Məqsədlər",
        enterCountry: "Ölkə Adını Daxil Edin",
        findCountry: "İstiqamətimi Tap",
        fromPlaceholder: "Şəhər və ya Ölkə",
        toPlaceholder: "Gedəcəyiniz Məkan",
        interestsPlaceholder: "Tarix, Təbiət, Macəra...",
        foodPlaceholder: "Veqan, Yerli, Restoran...",
        specialRequestsPlaceholder: "Xüsusi ehtiyaclar və ya özəl istəklər...",
        selectFoodType: "Yemək Üstünlüyü",
        searchBtn: "İndi Kəşf Et",
        backToDash: "Panelə Qayıt",
        days: "Gün",
        travelersLabel: "Səyyahlar",
        from: "Haradan",
        to: "Haraya",
        travelMode: "Səyahət Tipi",
        accommodationType: "Qalma Tipi",
        travelClass: "Təyyarə Sinifi",
        budgetPreference: "Büdcə Öncəliyi",
        season: "Mövsüm",
        specialRequests: "Xüsusi İstək",
        plane: "Təyyarə",
        car: "Avtomobil",
        bus: "Avtobus",
        train: "Qatar",
        luxury: "Lüks",
        standard: "Standart",
        eco: "Eko",
        economy: "Ekonom",
        business: "Biznes",
        firstClass: "Birinci Sinif",
        low: "Aşağı",
        medium: "Orta",
        high: "Yüksək",
        summer: "Yay",
        winter: "Qış",
        spring: "Yaz",
        autumn: "Payız",
        any: "İstənilən",

        // Plan Display
        recommended: "Tövsiyə olunan İstiqamətlər",
        breakdown: "Büdcə Bölgüsü",
        attractions: "Görməli Yerlər",
        foodRecs: "Qida Tövsiyələri",
        tips: "Səyahət Məsləhətləri",
        upgrade: "Təcrübənizi Yeniləyin",
        upgradeBtn: "İndi Yüksəlt",
        flight: "Uçuş",
        hotel: "Hotel",
        foodItem: "Qida",
        activities: "Fəaliyyətlər",

        // Gastro Guide Results
        budgetAnalysisReady: "Büdcə Təhlili Hazırdır",
        curatedByAgent: "TripMind Büdcə Agenti tərəfindən hazırlanıb",
        total: "Cəmi",

        // Service Cards
        explore: "Kəşf Et",
        tripPlannerTitle: "Səyahət Planlayıcı",
        tripPlannerDesc: "Zövqünüzə uyğun detallı marşrutlar və büdcə analizi.",
        gastroGuideTitle: "Qastro Bələdçi",
        gastroGuideDesc: "Səyahət xərclərinizi hesablayın və səfəriniz üçün ətraflı büdcə bölgüsü əldə edin.",
        spotFinderTitle: "Məkan Səyyahı",
        spotFinderDesc: "Hər hansı bir ölkənin ən məşhur və gizli yerlərini bir axtarışla üzə çıxarın.",
        foodFinderTitle: "Zövqünə Görə Yemək Tap",
        foodFinderDesc: "Olduğun ölkədə uyğun yeməyi kəşf et",
        foodCountryLabel: "Ölkə və Şəhər",
        foodCountrySubLabel: "Olduğunuz və ya gedəcəyiniz ölkə/şəhər",
        foodCountryPlaceholder: "Məsələn: Roma, İtaliya",
        foodTasteLabel: "Damaq dadı",
        foodBudgetLabel: "Büdcə",
        foodBudgetPlaceholder: "Büdcəni yaz",
        foodSpecialLabel: "Xüsusi tələblər",
        foodGenerateBtn: "Analiz Et",
        termsTitle: "İstifadə Şərtləri və Elmi İntellekt Siyasəti",
        termsIntro: "Sistemimiz qabaqcıl neyron-linqvistik modellər və statistik entropiya analizi üzərində çalışır.",
        termsSection1: "Süni İntellekt Etik Çərçivəsi",
        termsSection2: "Məlumat Trayektoriyası və Entropiya",
        termsSection3: "Alqoritmik Məsuliyyət",
        termsSection4: "Neyron Xəritələmə Dəqiqliyi",
        cookiesTitle: "Kuki Siyasəti",
        cookiesContent: "Sistemimiz 'sıfır izləmə' (zero-tracking) prinsipi ilə işləyir. Şəxsi sessiya məlumatlarınızı saxlamaq üçün heç bir kuki və ya yerli izləmə mexanizmlərindən istifadə olunmur.",
        privacyTitle: "Məxfilik Siyasəti və AI Xəbərdarlığı",
        privacyIntro: "Məlumatlarınızın məxfiliyi neyron işləmə etikası ilə tənzimlənir.",
        aiDisclaimer: "VACİB: Bu analiz Süni İntellekt tərəfindən yaradılmışdır. AI olduqca inkişaf etmiş olsa da, bəzən qeyri-dəqiq və ya köhnəlmiş məlumatlar verə bilər. Xahiş olunur vacib detalları müstəqil şəkildə yoxlayın.",
        termsS1Content: "TripMind AI neyron şəbəkələri mənəvi-etik seçim matrislərinə əsaslanır. Bizim alqoritmimiz insan mədəniyyətinin rəqəmsal ekvivalentini təhlil edərək, qlobal məlumat simbiozu yaradır. Hər bir tövsiyə, sosioloji determinizm prinsipləri ilə uzlaşdırılmışdır.",
        termsS2Content: "Məlumatların toplanması və işlənməsi statistik entropiyanın azaldılmasına hədəflənib. İstifadəçi girişləri kvant dayanıqlı şifrələmə ilə qorunur və neyron xəritələmə trayektoriyası boyunca anonim saxlanılır. Biz rəqəmsal xaosdan nizamlı səyahət strukturları yaradırıq.",
        termsS3Content: "Alqoritmik qərarlar avtonom olsa da, onlar makro-iqtisadi fluktuasiyalar və geosiyasi vektorlarla davamlı olaraq kalibrlənir. TripMind AI sistemindəki məlumatların 99.9% dəqiqliyi statistik ehtimal nəzəriyyəsi və empirik kross-validasiya ilə təmin edilir.",
        termsS4Content: "Neyron xəritələmə prosesi zamanı coğrafi koordinatların və mədəni artefaktların rəqəmsal əks olunması evristik modellər vasitəsilə həyata keçirilir. Biz istifadəçi təcrübəsini sadəcə planlaşdırmırıq, onu riyazi dəqiqliklə tərsim edirik.",
        scientificQuote: "İntellekt dəyişikliklərə uyğunlaşma qabiliyyətidir, lakin süni intellekt insan arzularının entropiyasını proqnozlaşdırmaq qabiliyyətidir.",
        privacyPoint1Title: "Məlumat Toplanması",
        privacyPoint1Desc: "Biz yalnız sizin analiz üçün daxil etdiyiniz parametrləri (ölkə, maraqlar və s.) emal edirik.",
        privacyPoint2Title: "Üçüncü Tərəflər",
        privacyPoint2Desc: "Məlumatlarınız heç bir reklam şirkətinə və ya kənar tərəfə satılmır. Analiz üçün yalnız AI modelləri (Groq/Gemini) istifadə olunur.",
        zeroStorageTitle: "Sıfır Saxlama Siyasəti",
        zeroStorageDesc: "Biz sizin şəxsi səyahət planlarınızı serverlərimizdə daimi olaraq saxlamırıq. Hər bir analiz müvəqqətidir və sessiya bitdikdə silinir.",
        favoritesTitle: "Sevimli Məkanlarım",
        favoritesSubtitle: "Arzuladığınız yerləri interaktiv dünya xəritəsində izləyin.",
        visitedCount: "Ziyarət Edilən",
        wishlistCount: "İstək Siyahısı",
        exploreMap: "Xəritəni Kəşf Et",
        addCountry: "Ölkə Əlavə Et",
        noFavorites: "Hələlik heç bir sevimli məkan əlavə etməmisiniz.",
        statsCompletion: "Yekun",
        chooseContinent: "Səyahət etmək istədiyin qitəni seç",
        englishLevel: "İngilis dili səviyyəni seç",
        budgetUSD: "Səyahət üçün büdcəni USD ilə daxil et",
        continentEurope: "Avropa",
        continentAsia: "Asiya",
        continentAfrica: "Afrika",
        continentNAmerica: "Şimali Amerika",
        continentSAmerica: "Cənubi Amerika",
        continentOceania: "Avstraliya/Okeaniya",
        tripArchitectTitle: "Ölkə Memarı",
        tripArchitectDesc: "Büdcənizə və dil səviyyənizə uyğun ən ideal ölkəni tapın.",
        tripArchitectSub: "Büdcənizə, yerləşdiyiniz yerə və dil səviyyənizə əsaslanan süni intellekt məntiqi.",
        architectureComplete: "Analiz Tamamlandı",
        calibratedByAI: "Sizin üçün fərdiləşdirilmiş süni intellekt təhlili",
        step: "Mərhələ",
        nextStep: "Növbəti",
        prevStep: "Geri",
        lastStep: "Sonuncu mərhələ",
        analyzeGenerate: "Analiz et və yarat",
        englishA1Desc: "Süni intellekt sizin üçün çox sadə cümlələrdən istifadə edəcək.",
        englishC2Desc: "Süni intellekt yüksək səviyyəli peşəkar təsvirlər təqdim edəcək.",
        englishDefaultDesc: "AI tövsiyə üslubunu sizin dil səviyyənizə uyğunlaşdıracaq.",
        recommendedCountryLabel: "Tövsiyə olunan ölkə",
        attractionsActivitiesLabel: "Atraksiyalar və Fəaliyyətlər",
        englishLevelAdviceLabel: "Dil Səviyyəsi Tövsiyəsi",
        budgetAnalysisAdviceLabel: "Büdcə Analizi və Məsləhətlər",
        tailoredNarrative: "DİL SƏVİYYƏNİZƏ UYĞUNLAŞDIRILMIŞ TƏSVİR",
        strategicTravelFinance: "Strateji Səyahət Maliyyəsi",

        // Food Taste Options
        tasteMeat: "Ət yeməkləri sevən",
        tasteVegetarian: "Vegetarian",
        tasteVegan: "Vegan",
        tasteSeafood: "Dəniz məhsulları sevən",
        tasteSweet: "Şirniyyat sevən",
        tasteSpicy: "Acı sevən",
        tasteHealthy: "Sağlam qidalanma",
        tasteStreet: "Street food sevən",
        tasteLuxury: "Lüks restoran sevən",
        tasteTraditional: "Yerli ənənəvi mətbəx",

        // Special Requirements Options
        reqHalal: "Halal lazımdır",
        reqGlutenFree: "Qlütensiz",
        reqLactoseFree: "Laktozsuz",
        reqAllergy: "Allergiyam var",

        // Tags
        meatLover: "Ət Sevən",
        vegetarian: "Vegetarian",
        vegan: "Veqan",
        halal: "Halal",
        history: "Tarix və Mədəniyyət",
        adventure: "Macəra və Təbiət",

        // Interest Tags
        interestAdventure: "Macəra",
        interestHistorian: "Tarixçi",
        interestNature: "Təbiətsevər",
        interestTech: "Texnoloji",
        interestSport: "İdmançı",
        interestMusic: "Musiqisevər",
        interestCinema: "Kinosevər",
        interestCreative: "Yaradıcı",
        interestTraveler: "Səyahətsevər",
        interestGastronome: "Qastronom",

        // Food Types
        foodMeat: "Ətli",
        foodMix: "Qarışıq",
        foodVegetarian: "Vegetarian",

        // Meals
        mealsPerDay: "Gündə Neçə Dəfə Yemək",

        // About Page
        aboutTitle: "Biz Kimik?",
        aboutDesc: "Biz səyahəti daha ağıllı, daha fərdi və daha əlçatan etmək üçün yaradılmış AI əsaslı platformayıq. Məqsədimiz insanların saatlarla araşdırma etmədən, büdcəsinə və zövqünə uyğun ideal səyahət planı əldə etməsidir.",
        aboutSystemDesc: "Sistemimiz istifadəçinin maraqlarını, büdcəsini, mədəni uyğunluğunu və hətta yemək zövqünü analiz edərək fərdi təkliflər hazırlayır.",
        missionTitle: "Missiyamız",
        missionDesc: "Hər kəs üçün fərdiləşdirilmiş və əlçatan səyahət təcrübəsi yaratmaq. Biz inanırıq ki, səyahət sadəcə yer dəyişmək deyil — doğru planlandıqda həyat təcrübəsidir.",
        howItWorksTitle: "Necə İşləyir?",
        howPoint1: "Büdcəni analiz edir",
        howPoint2: "Maraqlara uyğun istiqamətlər seçir",
        howPoint3: "Peşəyə görə xüsusi yerlər təklif edir",
        howPoint4: "Milli zövqə uyğun yeməklər tapır",
        howPoint5: "Real xərcləri təxmini hesablayır",
        howPoint6: "Mövsüm və tarixə uyğun optimizasiya edir",
        whyUsTitle: "Niyə Biz?",
        whyUsDesc: "Çünki biz sadəcə “hara getmək olar” demirik. Biz sənin kim olduğunu anlayırıq və səyahəti sənə uyğunlaşdırırıq.",
        visionTitle: "Gələcəyə Baxışımız",
        visionDesc: "Məqsədimiz AI əsaslı fərdi səyahət planlamanı qlobal səviyyədə əlçatan etmək və insanların səyahət qərarlarını daha rahat, daha sürətli və daha düzgün verməsinə kömək etməkdir.",
        // Footer Additional
        startExploring: "İndi Kəşf Et",
        welcome: "Xoş gəldiniz",
        planTitle: "Planınızı Seçin",
        freePlan: "Pulsuz",
        diamondPlan: "Almaz",
        goldPlan: "Qızıl",
        planMonth: "/ ay",
        planCurrent: "Cari Plan",
        planUpgrade: "Yüksəlt",
        planFreeF1: "Gündə 3 AI Plan",
        planFreeF2: "Əsas istiqamətlər",
        planFreeF3: "Standart dəstək",
        planDiamondF1: "Gündə 30 AI Plan",
        planDiamondF2: "Bütün istiqamətlər",
        planDiamondF3: "Prioritet dəstək",
        planDiamondF4: "Büdcə analitikası",
        planGoldF1: "Limitsiz AI Plan",
        planGoldF2: "Bütün istiqamətlər",
        planGoldF3: "24/7 VIP dəstək",
        planGoldF4: "Tam analitika",
        planGoldF5: "Fərdi marşrutlar",
        company: "Şirkət",
        supportText: "Dəstək",
        privacyPolicy: "Məxfilik Siyasəti",
        contact: "Əlaqə",
        helpCenter: "Yardım Mərkəzi",
        community: "İcma",
        feedback: "Rəy",
        footerTagline: "AI Əsaslı Səyahət Zəkası",
        footerSubtitle: "Qlobal kəşfiyyatın gələcəyini təcrübə edin.",
        security: "Təhlükəsizlik",
        terms: "Şərtlər",
        systemsOperational: "Sistemlər Aktivdir",
        brandSubtitle: "Global AI Memar",
    },
    ru: {
        // Project Info
        projectName: "TripMind AI",
        tagline: "Ваш личный ИИ-помощник в путешествиях",

        // Navigation
        home: "Главная",
        about: "О нас",
        favorites: "Избранное",
        profile: "Профиль",

        // Auth placeholder removed

        // Hero
        heroTitle: "Ваш личный ИИ-архитектор путешествий",
        heroSubtitle: "Глубоко персонализированные маршруты, созданные искусственным интеллектом.",
        analyzing: "Анализируем ваш профиль...",
        calculating: "Рассчитывается...",
        startNew: "Начать новый анализ",
        generateBtn: "Создать глубокий план поездки",
        travelDate: "Дата поездки",

        // Forms
        budget: "Бюджет",
        dates: "Даты",
        nationality: "Гражданство",
        location: "Местоположение",
        profession: "Профессия",
        food: "Предпочтения в еде",
        interests: "Интересы",
        special: "Особые запросы",
        planSettings: "Настройки плана",
        travelBasics: "Основы поездки",
        personalDetails: "Личные данные",
        preferences: "Предпочтения",
        goals: "Интересы и цели",
        enterCountry: "Введите название страны",
        findCountry: "Найти Направление",
        fromPlaceholder: "Город или Страна",
        toPlaceholder: "Место назначения",
        interestsPlaceholder: "История, Природа, Приключения...",
        foodPlaceholder: "Веган, Местная кухня, Рестораны...",
        specialRequestsPlaceholder: "Особые потребности или пожелания...",
        selectFoodType: "Предпочтения в еде",
        searchBtn: "Найти Сейчас",
        backToDash: "Вернуться назад",
        days: "Дней",
        travelersLabel: "Путешественники",
        from: "Откуда",
        to: "Куда",
        travelMode: "Тип путешествия",
        accommodationType: "Тип проживания",
        travelClass: "Класс перелета",
        budgetPreference: "Бюджетный приоритет",
        season: "Сезон",
        specialRequests: "Особые запросы",
        plane: "Самолет",
        car: "Машина",
        bus: "Автобус",
        train: "Поезд",
        luxury: "Люкс",
        standard: "Стандарт",
        eco: "Эко",
        economy: "Эконом",
        business: "Бизнес",
        firstClass: "Первый класс",
        low: "Низкий",
        medium: "Средний",
        high: "Высокий",
        summer: "Лето",
        winter: "Зима",
        spring: "Весна",
        autumn: "Осень",
        any: "Любой",

        // Plan Display
        recommended: "Рекомендуемые направления",
        breakdown: "Разбивка бюджета",
        attractions: "Главные достопримечательности",
        foodRecs: "Рекомендации по еде",
        tips: "Советы для путешественников",
        upgrade: "Улучшите свой опыт",
        upgradeBtn: "Повысить уровень",
        flight: "Перелет",
        hotel: "Отель",
        foodItem: "Еда",
        activities: "Активности",

        // Gastro Guide Results
        budgetAnalysisReady: "Анализ Бюджета Готов",
        curatedByAgent: "Подготовлено агентом TripMind Budget",
        total: "Итого",

        // Service Cards
        explore: "Исследовать",
        tripPlannerTitle: "Планировщик",
        tripPlannerDesc: "Детальные маршруты и анализ бюджета специально для вас.",
        gastroGuideTitle: "Гастро-гид",
        gastroGuideDesc: "Рассчитайте свои расходы на поездку и получите подробную разбивку бюджета.",
        spotFinderTitle: "Исследователь Мест",
        spotFinderDesc: "Откройте самые знаковые и скрытые достопримечательности любой страны.",
        foodFinderTitle: "Поиск Еды",
        foodFinderDesc: "Откройте для себя идеальную еду в стране, в которой вы находитесь.",
        foodCountryLabel: "Страна и Город",
        foodCountrySubLabel: "Страна/город, в котором вы находитесь или куда собираетесь",
        foodCountryPlaceholder: "Например: Рим, Италия",
        foodTasteLabel: "Вкусовые предпочтения",
        foodBudgetLabel: "Бюджет",
        foodBudgetPlaceholder: "Напишите ваш бюджет",
        foodSpecialLabel: "Особые требования",
        foodGenerateBtn: "Анализировать",
        termsTitle: "Условия использования и Политика научного интеллекта",
        termsIntro: "Наша система работает на основе передовых нейролингвистических моделей и анализа статистической энтропии.",
        termsSection1: "Этическая база ИИ",
        termsSection2: "Траектория данных и энтропия",
        termsSection3: "Алгоритмическая ответственность",
        termsSection4: "Точность нейронного картирования",
        cookiesTitle: "Политика использования куки",
        cookiesContent: "Наша система работает по принципу «нулевого отслеживания». Мы не используем куки или механизмы локального отслеживания для хранения ваших личных данных сессии.",
        privacyTitle: "Политика конфиденциальности и раскрытие ИИ",
        privacyIntro: "Конфиденциальность ваших данных регулируется этикой нейронной обработки.",
        aiDisclaimer: "ВАЖНО: Этот анализ создан Искусственным Интеллектом. Несмотря на высокую продвинутость, ИИ иногда может предоставлять неточную или устаревшую информацию. Пожалуйста, проверяйте важные детали самостоятельно.",
        termsS1Content: "Нейронные сети TripMind AI основаны на морально-этических матрицах выбора. Наш алгоритм анализирует цифровой эквивалент человеческой культуры для создания глобального симбиоза данных. Каждая рекомендация согласована с принципами социологического детерминизма.",
        termsS2Content: "Сбор и обработка данных направлены на снижение статистической энтропии. Пользовательские данные защищены квантово-устойчивым шифрованием и остаются анонимными на протяжении всей траектории нейронного картирования. Мы создаем упорядоченные структуры путешествий из цифрового хаоса.",
        termsS3Content: "Хотя алгоритмические решения автономны, они постоянно калибруются с учетом макроэкономических флуктуаций и геополитических векторов. Точность данных TripMind AI на 99,9% обеспечивается теорией статистической вероятности и эмпирической кросс-валидацией.",
        termsS4Content: "В процессе нейронного картирования цифровое отражение географических координат и культурных артефактов осуществляется с помощью эвристических моделей. Мы не просто планируем пользовательский опыт; мы реконструируем его с математической точностью.",
        scientificQuote: "Интеллект — это способность адаптироваться к изменениям, но искусственный интеллект — это способность предсказывать энтропию человеческих желаний.",
        privacyPoint1Title: "Сбор данных",
        privacyPoint1Desc: "Мы обрабатываем только параметры, которые вы вводите для анализа (страна, интересы и т.д.).",
        privacyPoint2Title: "Третьи стороны",
        privacyPoint2Desc: "Ваши данные не продаются никаким рекламным компаниям или третьим лицам. Для анализа используются только модели ИИ (Groq/Gemini).",
        zeroStorageTitle: "Политика нулевого хранения",
        zeroStorageDesc: "Мы не храним ваши личные планы путешествий постоянно на наших серверах. Каждый анализ является временным и удаляется по окончании сессии.",
        favoritesTitle: "Мои любимые места",
        favoritesSubtitle: "Отслеживайте места своей мечты на интерактивной карте мира.",
        visitedCount: "Посещенные страны",
        wishlistCount: "Список желаний",
        exploreMap: "Исследовать карту",
        addCountry: "Добавить страну",
        noFavorites: "Вы еще не добавили ничего в избранное.",
        statsCompletion: "Завершение",
        chooseContinent: "Выберите континент для путешествия",
        englishLevel: "Выберите ваш уровень английского",
        budgetUSD: "Введите бюджет путешествия в USD",
        continentEurope: "Европа",
        continentAsia: "Азия",
        continentAfrica: "Африка",
        continentNAmerica: "Северная Америка",
        continentSAmerica: "Южная Америка",
        continentOceania: "Австралия/Океания",
        tripArchitectTitle: "Архитектор стран",
        tripArchitectDesc: "Найдите идеальную страну на основе вашего бюджета и уровня английского.",
        tripArchitectSub: "Логика ИИ для поиска идеального направления на основе бюджета, локации и знания языка.",
        architectureComplete: "Архитектура готова",
        calibratedByAI: "Специально откалибровано для вас ИИ",
        step: "Шаг",
        nextStep: "Следующий шаг",
        prevStep: "Назад",
        lastStep: "Последний шаг",
        analyzeGenerate: "Анализировать и создать",
        englishA1Desc: "ИИ будет использовать очень простые предложения для вас.",
        englishC2Desc: "ИИ предоставит профессиональное повествование высокого уровня.",
        englishDefaultDesc: "ИИ подстроит стиль рекомендаций под ваш уровень владения языком.",
        recommendedCountryLabel: "Рекомендуемая страна",
        attractionsActivitiesLabel: "Достопримечательности и активности",
        englishLevelAdviceLabel: "Совет по уровню английского",
        budgetAnalysisAdviceLabel: "Анализ бюджета и советы",
        tailoredNarrative: "ИНДИВИДУАЛЬНОЕ ПОВЕСТВОВАНИЕ ПОД ВАШ УРОВЕНЬ",
        strategicTravelFinance: "Стратегические финансы в путешествиях",

        // Food Taste Options
        tasteMeat: "Любитель мяса",
        tasteVegetarian: "Вегетарианец",
        tasteVegan: "Веган",
        tasteSeafood: "Любитель морепродуктов",
        tasteSweet: "Любитель сладкого",
        tasteSpicy: "Любитель острого",
        tasteHealthy: "Здоровое питание",
        tasteStreet: "Любитель уличной еды",
        tasteLuxury: "Любитель люкс ресторанов",
        tasteTraditional: "Традиционная местная кухня",

        // Special Requirements Options
        reqHalal: "Нужен Халяль",
        reqGlutenFree: "Без глютена",
        reqLactoseFree: "Без лактозы",
        reqAllergy: "У меня аллергия",

        // Tags
        meatLover: "Любитель мяса",
        vegetarian: "Вегетарианец",
        vegan: "Веган",
        halal: "Халяль",
        history: "История и Культура",
        adventure: "Приключения и Природа",

        // Interest Tags
        interestAdventure: "Авантюрист",
        interestHistorian: "Историк",
        interestNature: "Любитель природы",
        interestTech: "Технолог",
        interestSport: "Спортсмен",
        interestMusic: "Меломан",
        interestCinema: "Киноман",
        interestCreative: "Творческий",
        interestTraveler: "Путешественник",
        interestGastronome: "Гастроном",

        // Food Types
        foodMeat: "Мясо",
        foodMix: "Микс",
        foodVegetarian: "Вегетарианское",

        // Meals
        mealsPerDay: "Приёмов пищи в день",

        // About Page
        aboutTitle: "Кто Мы?",
        aboutDesc: "Мы — платформа на базе ИИ, созданная для того, чтобы сделать путешествия умнее, индивидуальнее и доступнее. Наша цель — чтобы люди находили свой идеальный план путешествия на основе своего бюджета и вкуса без многочасовых исследований.",
        aboutSystemDesc: "Наша система подготавливает индивидуальные предложения, анализируя интересы пользователя, бюджет, культурную совместимость и даже вкусовые предпочтения.",
        missionTitle: "Наша Миссия",
        missionDesc: "Создание персонализированного и доступного туристического опыта для каждого. Мы верим, что путешествие — это не просто смена места, а жизненный опыт при правильном планировании.",
        howItWorksTitle: "Как Это Работает?",
        howPoint1: "Анализирует бюджет",
        howPoint2: "Выбирает направления по интересам",
        howPoint3: "Предлагает особые места по профессии",
        howPoint4: "Находит еду по национальному вкусу",
        howPoint5: "Оценивает реальные расходы",
        howPoint6: "Оптимизирует по сезону и дате",
        whyUsTitle: "Почему Мы?",
        whyUsDesc: "Потому что мы не просто говорим «куда можно поехать». Мы понимаем, кто вы, и адаптируем путешествие под вас.",
        visionTitle: "Наше Видение Будущего",
        visionDesc: "Наша цель — сделать персональное планирование путешествий на базе ИИ доступным на глобальном уровне и помочь людям принимать решения о путешествиях проще, быстрее и правильнее.",
        // Footer Additional
        startExploring: "Начать Исследовать",
        welcome: "Добро пожаловать",
        planTitle: "Выберите план",
        freePlan: "Бесплатно",
        diamondPlan: "Бриллиант",
        goldPlan: "Золото",
        planMonth: "/ мес",
        planCurrent: "Текущий план",
        planUpgrade: "Улучшить",
        planFreeF1: "3 ИИ-плана / день",
        planFreeF2: "Базовые направления",
        planFreeF3: "Стандартная поддержка",
        planDiamondF1: "30 ИИ-планов / день",
        planDiamondF2: "Все направления",
        planDiamondF3: "Приоритетная поддержка",
        planDiamondF4: "Аналитика бюджета",
        planGoldF1: "Безлимитные ИИ-планы",
        planGoldF2: "Все направления",
        planGoldF3: "VIP поддержка 24/7",
        planGoldF4: "Полная аналитика",
        planGoldF5: "Личные маршруты",
        company: "Компания",
        supportText: "Поддержка",
        privacyPolicy: "Политика конфиденциальности",
        contact: "Контакт",
        helpCenter: "Центр помощи",
        community: "Сообщество",
        feedback: "Обратная связь",
        footerTagline: "Интеллект Путешествий на базе ИИ",
        footerSubtitle: "Испытайте будущее глобальных открытий.",
        security: "Безопасность",
        terms: "Условия",
        systemsOperational: "Системы Активны",
        brandSubtitle: "Глобальный ИИ-Архитектор",
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>("az");
    const [isInitialized, setIsInitialized] = useState(false);

    // Initial load
    useEffect(() => {
        const savedLang = localStorage.getItem("app_lang") as Language;
        if (savedLang && (savedLang === "en" || savedLang === "az" || savedLang === "ru")) {
            setLanguageState(savedLang);
        }
        setIsInitialized(true);
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("app_lang", lang);
    };

    const t = (key: string) => {
        return (translations[language] as any)[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
